import { Link, useParams } from 'react-router-dom';
import SEO from '../components/SEO';
import { ArrowRight, CheckCircle2 } from 'lucide-react';

const pages = {
  'resume-builder-for-freshers': { title: 'Resume Builder for Freshers', description: 'Build an entry-level resume around education, projects, internships, skills, and evidence you can discuss.', intro: 'A fresher resume should make potential visible without pretending you have years of experience. ResumeCraft helps you organize your education, projects, coursework, internships, certifications, and strengths into a clean, reviewable document.', points: ['Lead with projects or internships when they are your strongest evidence.', 'Use a short role-specific summary instead of a generic objective.', 'Choose skills you can explain in an interview and keep links current.'], links: [['BCA fresher example', '/resume-examples/bca-fresher'], ['Fresher templates', '/resume-templates/fresher']] },
  'resume-builder-for-students': { title: 'Resume Builder for Students', description: 'Create a student resume for internships and entry-level roles with projects, campus work, and education.', intro: 'Students often have more evidence than they realize: class projects, research, volunteering, societies, competitions, and part-time work can all show useful skills when described clearly.', points: ['Explain your contribution to a project, not only the project title.', 'Keep education details easy to scan and update the dates carefully.', 'Use volunteering and campus leadership when it demonstrates relevant responsibility.'], links: [['Student templates', '/resume-templates/student'], ['Resume examples', '/resume-examples']] },
  'resume-builder-india': { title: 'Resume Builder for India', description: 'Create an ATS-readable resume for Indian students, freshers, and professionals with flexible contact and education fields.', intro: 'ResumeCraft is designed for the way many Indian candidates build resumes: education matters, early-career projects are important, and applications may ask for a concise PDF that is easy to read on mobile and desktop.', points: ['Use a professional email address and a reachable phone number.', 'Include city and country when location is relevant to the role.', 'Keep your resume focused; add personal details only when they are relevant or requested.'], links: [['BCA fresher format', '/resume-format-for-bca-students'], ['Engineering student format', '/resume-format-for-engineering-students']] },
  'resume-format-for-freshers': { title: 'Resume Format for Freshers', description: 'A practical resume format for freshers that keeps skills, projects, education, and internships readable.', intro: 'The best fresher format is not the one with the most decoration. It is the one that helps a reviewer understand what you know, what you built, and what you are ready to learn next.', points: ['Use one clear column when ATS readability is your priority.', 'Put projects before experience if projects provide stronger evidence.', 'Use action verbs and real outcomes; never invent metrics.'], links: [['Fresher resume example', '/resume-examples/bca-fresher'], ['ATS templates', '/resume-templates/ats']] },
  'resume-format-for-bca-students': { title: 'Resume Format for BCA Students', description: 'A project-first BCA resume format for students and fresh graduates applying to software and analyst roles.', intro: 'A BCA resume can show practical readiness through web projects, database work, programming fundamentals, internships, and coursework. Focus on what you actually built and learned.', points: ['Name the languages, frameworks, and tools you genuinely used.', 'Describe project scope and your personal contribution in two or three lines.', 'Keep education, certifications, and relevant coursework concise.'], links: [['BCA fresher example', '/resume-examples/bca-fresher'], ['Software engineer example', '/resume-examples/software-engineer']] },
  'resume-format-for-mba-students': { title: 'Resume Format for MBA Students', description: 'A clear MBA resume format for internships, campus placements, and early-career business roles.', intro: 'MBA candidates can use live projects, internships, case competitions, coursework, and leadership to show structured thinking. Make the business question and your role clear.', points: ['Explain the problem, your contribution, and the recommendation.', 'Separate team outcomes from your individual work.', 'Prioritize the target function instead of listing every business keyword.'], links: [['MBA resume example', '/resume-examples/mba'], ['Professional templates', '/resume-templates/professional']] },
  'resume-format-for-engineering-students': { title: 'Resume Format for Engineering Students', description: 'A practical engineering student resume format for projects, internships, technical skills, and placements.', intro: 'Engineering students can build a strong application around technical projects, labs, internships, competitions, and relevant coursework. Clarity matters more than dense terminology.', points: ['Group technical skills so a reviewer can see your focus quickly.', 'Use projects to demonstrate engineering decisions and trade-offs.', 'Keep the document concise and check every date, link, and result.'], links: [['Software engineer example', '/resume-examples/software-engineer'], ['Student templates', '/resume-templates/student']] },
  'ats-resume-for-freshers': { title: 'ATS Resume Guide for Freshers', description: 'Understand ATS-readable formatting and review a fresher resume without relying on pass-or-fail promises.', intro: 'Applicant tracking systems can make the first pass of an application more structured, but no score guarantees an interview. Use clean headings, ordinary text, relevant keywords, and truthful evidence.', points: ['Prefer readable headings such as Education, Skills, Projects, and Experience.', 'Compare the job description with skills you genuinely have.', 'Review the exported PDF for clipping, missing text, and inconsistent spacing.'], links: [['ATS template category', '/resume-templates/ats'], ['Open ATS guidance', '/ats-resume-checker-preview']] },
  'resume-builder-for-career-changers': { title: 'Resume Builder for Career Changers', description: 'Reframe transferable skills, projects, and achievements into a focused resume for a new career direction.', intro: 'A career-change resume does not need to hide your previous experience. It should make the connection between what you have done and what your target role needs easy to understand.', points: ['Lead with transferable strengths and evidence that match the new role.', 'Use projects, courses, and volunteer work to close specific experience gaps.', 'Explain the transition in a short, confident summary rather than a long personal story.'], links: [['Business analyst template', '/resume-template/business-analyst'], ['Resume score checker', '/resume-score-checker']] },
  'resume-builder-for-internships': { title: 'Resume Builder for Internships', description: 'Create an internship resume with projects, coursework, campus work, and skills that show readiness to learn.', intro: 'An internship resume should show how you learn, contribute, and take responsibility. Projects, coursework, clubs, competitions, and part-time work can all become useful evidence when the context is clear.', points: ['Put relevant projects and coursework near the top when you have limited experience.', 'Explain your contribution and tools instead of listing project titles only.', 'Use a clean one-page layout and keep links, dates, and contact details current.'], links: [['Student resume format', '/resume-builder-for-students'], ['Fresher guide', '/blog/fresher-resume-projects-no-experience']] },
  'resume-builder-for-tech-jobs': { title: 'Resume Builder for Technology Jobs', description: 'Build a technology resume around projects, systems, tools, measurable outcomes, and the role you want next.', intro: 'Technology hiring teams need to understand what you built, how you contributed, and which technical decisions you can explain. A focused resume is more useful than a long list of every tool you have seen.', points: ['Choose the role first, then prioritize the skills and projects that support it.', 'Describe APIs, systems, data, testing, or design decisions with practical context.', 'Use a portfolio, GitHub, or project link only when it is maintained and reviewable.'], links: [['Software engineer template', '/resume-template/software-engineer'], ['Full stack template', '/resume-template/full-stack-developer']] },
};

const AudienceLanding = () => {
  const { slug } = useParams();
  const page = pages[slug] || pages['resume-builder-for-freshers'];
  return <div className="bg-white"><SEO title={page.title} description={page.description} keywords={`${page.title}, resume builder, ATS-friendly resume`} /><section className="bg-slate-950 px-4 py-20 text-white"><div className="mx-auto max-w-5xl"><p className="text-xs font-black uppercase tracking-[0.2em] text-orange-300">ResumeCraft career guide</p><h1 className="mt-4 max-w-4xl text-4xl font-black tracking-tight sm:text-6xl">{page.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">{page.description}</p><Link to="/editor" className="mt-8 inline-flex items-center rounded-2xl bg-orange-500 px-5 py-3.5 text-sm font-black text-white hover:bg-orange-400">Create your resume <ArrowRight className="ml-2 h-4 w-4" /></Link></div></section><main className="mx-auto max-w-5xl px-4 py-14"><div className="grid gap-12 md:grid-cols-[1.1fr_0.9fr]"><section><h2 className="text-2xl font-black text-slate-950">A practical starting point</h2><p className="mt-5 text-base leading-8 text-slate-600">{page.intro}</p><h2 className="mt-12 text-2xl font-black text-slate-950">What to focus on</h2><div className="mt-5 space-y-4">{page.points.map((point) => <p key={point} className="flex gap-3 text-sm leading-7 text-slate-600"><CheckCircle2 className="mt-1 h-5 w-5 shrink-0 text-emerald-500" />{point}</p>)}</div></section><aside className="rounded-3xl border border-slate-200 bg-slate-50 p-6"><p className="text-xs font-black uppercase tracking-wider text-orange-500">Continue learning</p><div className="mt-5 space-y-3">{page.links.map(([label, href]) => <Link key={href} to={href} className="flex items-center justify-between rounded-2xl bg-white p-4 text-sm font-black text-slate-800 shadow-sm ring-1 ring-slate-200 hover:text-orange-600">{label}<ArrowRight className="h-4 w-4" /></Link>)}</div><div className="mt-7 border-t border-slate-200 pt-5"><Link to="/resume-examples" className="text-sm font-black text-orange-600">Browse all examples</Link><span className="mx-2 text-slate-300">·</span><Link to="/resume-templates" className="text-sm font-black text-orange-600">Browse all templates</Link></div></aside></div></main></div>;
};

export default AudienceLanding;
