import { Link } from 'react-router-dom';
import SEO from '../components/SEO';
import { ArrowRight, CheckCircle2 } from 'lucide-react';

const examples = [
  { title: 'Software Engineer Cover Letter Example', description: 'A structured example for connecting technical work to the role without repeating the resume.', points: ['Open with the target role and a specific reason for applying.', 'Choose one or two relevant projects or responsibilities.', 'Close with a clear, professional next step.'] },
  { title: 'Fresher Cover Letter Example', description: 'A practical starting point for students and fresh graduates with projects, coursework, and internships.', points: ['Use education and projects as evidence rather than apologizing for limited experience.', 'Explain what you contributed personally.', 'Keep the tone confident, specific, and honest.'] },
  { title: 'Career Change Cover Letter Example', description: 'A focused framework for explaining transferable skills and the reason for a change.', points: ['Name the direction you are moving toward.', 'Connect previous work to the target role’s needs.', 'Avoid unsupported claims about results or expertise.'] },
];

const CoverLetterExamples = () => <div className="bg-white"><SEO title="Cover Letter Examples" description="Practical cover letter examples for software engineers, freshers, and career changers." keywords="cover letter examples, fresher cover letter, software engineer cover letter" /><section className="bg-slate-950 px-4 py-20 text-white"><div className="mx-auto max-w-5xl"><p className="text-xs font-black uppercase tracking-[0.2em] text-orange-300">Career writing</p><h1 className="mt-4 text-4xl font-black tracking-tight sm:text-6xl">Cover letter examples that stay specific</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Use these structures to explain fit and motivation without copying your resume or inventing achievements.</p><Link to="/cover-letter-builder" className="mt-8 inline-flex items-center rounded-2xl bg-orange-500 px-5 py-3.5 text-sm font-black text-white hover:bg-orange-400">Open cover letter builder <ArrowRight className="ml-2 h-4 w-4" /></Link></div></section><main className="mx-auto max-w-5xl px-4 py-14"><div className="grid gap-5 md:grid-cols-3">{examples.map((example) => <article key={example.title} className="rounded-3xl border border-slate-200 p-6 shadow-sm"><h2 className="text-xl font-black text-slate-950">{example.title}</h2><p className="mt-3 text-sm leading-7 text-slate-600">{example.description}</p><div className="mt-5 space-y-3">{example.points.map((point) => <p key={point} className="flex gap-2 text-sm leading-6 text-slate-600"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-emerald-500" />{point}</p>)}</div></article>)}</div><div className="mt-12 rounded-3xl border border-orange-100 bg-orange-50 p-7"><h2 className="text-2xl font-black text-orange-950">A simple workflow</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-orange-900">Choose a resume, paste the job description, select a tone, generate a draft, and review every sentence before downloading. AI should help you express your facts, not replace them.</p><Link to="/cover-letter-builder" className="mt-5 inline-flex items-center font-black text-orange-700">Create a cover letter <ArrowRight className="ml-2 h-4 w-4" /></Link></div></main></div>;

export default CoverLetterExamples;
