import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { Copy, FileText, History, Loader2, Mail, Sparkles, Target, Trash2 } from 'lucide-react';
import SEO from '../components/SEO';
import JobMatchScoreBreakdown from '../components/JobMatchScoreBreakdown';
import api from '../api/axios';
import AuthContext from '../context/AuthContext';
import { useContext } from 'react';

const starterResume = `Frontend Developer\nReact JavaScript HTML CSS Git\nBuilt responsive React interfaces and reusable components.\nCreated a student dashboard with form validation and API integration.\nCollaborated with designers and tested user flows.`;
const starterJob = `We are hiring a Frontend Developer to build accessible React applications. You will work with JavaScript, REST APIs, Git, responsive design, testing, and cross-functional teams. Experience with TypeScript is preferred.`;
const skills = ['react', 'javascript', 'typescript', 'html', 'css', 'git', 'rest api', 'api integration', 'responsive design', 'testing', 'accessibility', 'teamwork', 'collaboration', 'sql', 'python', 'figma'];
const label = s => s.replace(/\b\w/g, c => c.toUpperCase());
function localAnalyse(resume, job) { const r = resume.toLowerCase(); const j = job.toLowerCase(); const terms = skills.filter(s => j.includes(s)); const matched = terms.filter(s => r.includes(s)); const missing = terms.filter(s => !r.includes(s)); const keyword = terms.length ? Math.round(matched.length / terms.length * 100) : 0; const responsibility = Math.min(100, 45 + (r.match(/built|created|develop|collaborat|tested|worked/gi) || []).length * 9); const clarity = Math.min(100, 48 + Math.min(52, Math.round(resume.length / 18))); return { score: Math.round(keyword * .5 + responsibility * .3 + clarity * .2), matched: matched.map(label), missing: missing.map(label), unclear: [], breakdown: [{ label: 'Skills alignment', value: keyword }, { label: 'Responsibility evidence', value: responsibility }, { label: 'Resume clarity', value: clarity }, { label: 'Role relevance', value: Math.round((keyword + responsibility) / 2) }] }; }
function normalize(result) { if (result.breakdown) return result; const score = result.score || 0; return { score, matched: (result.matchedSkills || []).map(label), missing: (result.missingSkills || []).map(label), unclear: [], breakdown: [{ label: 'Keyword alignment', value: score }, { label: 'Relevant evidence', value: Math.max(0, score - 5) }, { label: 'Resume clarity', value: Math.min(100, score + 12) }, { label: 'Role relevance', value: score }] }; }

export default function JobMatch() {
  const { user } = useContext(AuthContext);
  const [resume, setResume] = useState(() => localStorage.getItem('rc-job-resume') || starterResume);
  const [job, setJob] = useState(() => localStorage.getItem('rc-job-description') || starterJob);
  const [company, setCompany] = useState(''); const [jobUrl, setJobUrl] = useState(''); const [status, setStatus] = useState('Saved');
  const [result, setResult] = useState(null); const [versions, setVersions] = useState([]); const [versionName, setVersionName] = useState(''); const [coverLetter, setCoverLetter] = useState(null); const [loading, setLoading] = useState(false); const [letterLoading, setLetterLoading] = useState(false); const [notice, setNotice] = useState('');
  const canAnalyse = resume.trim().length > 40 && job.trim().length > 40;
  const jobTitle = useMemo(() => (job.match(/(frontend|backend|software|data|marketing|product|customer support)[^\n,.]*/i)?.[0] || 'Target role').trim(), [job]);
  useEffect(() => { if (user) api.get('/job-matches').then(({ data }) => setVersions(data)).catch(() => setNotice('Sign in again to load saved job matches.')); }, [user]);
  const run = async () => { setLoading(true); try { const { data } = await api.post('/ai/match-job', { resume, jobDescription: job }); const normalized = normalize(data); setResult(normalized); localStorage.setItem('rc-job-resume', resume); localStorage.setItem('rc-job-description', job); setNotice('Match analysis complete.'); } catch { setResult(localAnalyse(resume, job)); setNotice('Using local analysis; the server match service was unavailable.'); } finally { setLoading(false); } };
  const saveMatch = async (extra = {}) => { const payload = { title: versionName.trim() || `${jobTitle} — tailored`, company, jobUrl, jobDescription: job, resumeText: resume, matchResult: result, status, coverLetter: extra.coverLetter || coverLetter }; if (user) { const { data } = await api.post('/job-matches', payload); setVersions(prev => [data, ...prev.filter(item => item._id !== data._id)]); setNotice('Saved permanently to your account.'); } else { const item = { ...payload, _id: `local-${Date.now()}`, createdAt: new Date().toISOString() }; const next = [item, ...JSON.parse(localStorage.getItem('rc-resume-versions') || '[]')]; localStorage.setItem('rc-resume-versions', JSON.stringify(next)); setVersions(next); setNotice('Saved in this browser. Sign in to sync across devices.'); } setVersionName(''); };
  const updateStatus = async (item, nextStatus) => { setStatus(nextStatus); if (user && item._id) { const { data } = await api.put(`/job-matches/${item._id}`, { status: nextStatus }); setVersions(prev => prev.map(v => v._id === item._id ? data : v)); } };
  const remove = async item => { if (user && item._id) { await api.delete(`/job-matches/${item._id}`); setVersions(prev => prev.filter(v => v._id !== item._id)); } else { const next = versions.filter(v => v._id !== item._id); setVersions(next); localStorage.setItem('rc-resume-versions', JSON.stringify(next)); } };
  const generateLetter = async () => { setLetterLoading(true); try { const { data } = await api.post('/ai/generate-cover-letter', { jobRole: jobTitle, jobDescription: job, userName: user?.name, companyName: company, userTitle: jobTitle, tone: 'Professional and specific' }); setCoverLetter(data); if (user && versions[0]?._id) { const saved = await api.put(`/job-matches/${versions[0]._id}`, { coverLetter: data }); setVersions(prev => prev.map(v => v._id === saved.data._id ? saved.data : v)); } setNotice('Cover letter generated. Review every claim before sending.'); } catch { setNotice('Cover-letter generation is temporarily unavailable.'); } finally { setLetterLoading(false); } };
  const load = item => { setResume(item.resumeText); setJob(item.jobDescription); setCompany(item.company || ''); setJobUrl(item.jobUrl || ''); setStatus(item.status || 'Saved'); setResult(item.matchResult ? normalize(item.matchResult) : null); setCoverLetter(item.coverLetter || null); setNotice(`${item.title} loaded.`); };
  return <><SEO title="Job Description Resume Matcher | ResumeCraft" description="Compare your resume with a job description, save tailored versions, track application status, and generate a tailored cover letter." canonical="https://resumecraft.co.in/job-match" /><main className="min-h-screen bg-[#fffaf5] px-4 pb-20 pt-12 text-slate-900 sm:px-6"><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-[1.15fr_.85fr] lg:items-end"><div><p className="text-xs font-black uppercase tracking-[0.24em] text-orange-600">Application workspace</p><h1 className="mt-4 max-w-4xl text-4xl font-black tracking-tight sm:text-6xl">Make every application feel intentionally written.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-600">Compare, tailor, save, write, and track one application without overwriting your master resume.</p></div><div className="rounded-3xl bg-slate-950 p-6 text-white shadow-xl"><div className="flex items-center gap-3"><Target className="text-orange-400" /><div><p className="text-sm font-black">{user ? 'Cloud-synced workspace' : 'Local-first workspace'}</p><p className="mt-1 text-sm leading-6 text-slate-300">{user ? 'Your saved matches follow your account.' : 'Sign in to permanently save and sync versions.'}</p></div></div></div></div>
  <div className="mt-10 grid gap-6 lg:grid-cols-[1fr_1fr]"><section className="rounded-3xl border border-orange-100 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center justify-between"><h2 className="text-xl font-black">1. Your resume evidence</h2><FileText className="text-orange-500" /></div><textarea value={resume} onChange={e => setResume(e.target.value)} className="mt-5 min-h-72 w-full rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm leading-6 outline-none focus:border-orange-400 focus:ring-4 focus:ring-orange-100" aria-label="Resume content" /></section><section className="rounded-3xl border border-orange-100 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center justify-between"><h2 className="text-xl font-black">2. Job description</h2><Sparkles className="text-orange-500" /></div><textarea value={job} onChange={e => setJob(e.target.value)} className="mt-5 min-h-72 w-full rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm leading-6 outline-none focus:border-orange-400 focus:ring-4 focus:ring-orange-100" aria-label="Job description" /></section></div>
  <div className="mt-6 grid gap-3 md:grid-cols-3"><input value={company} onChange={e => setCompany(e.target.value)} placeholder="Company (optional)" className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm" /><input value={jobUrl} onChange={e => setJobUrl(e.target.value)} placeholder="Job URL (optional)" className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm" /><select value={status} onChange={e => setStatus(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm"><option>Saved</option><option>Applied</option><option>Screening</option><option>Interview</option><option>Offer</option><option>Rejected</option></select></div>
  <div className="mt-6 flex flex-wrap items-center gap-3"><button onClick={run} disabled={!canAnalyse || loading} className="rounded-2xl bg-orange-500 px-6 py-3.5 text-sm font-black text-white shadow-lg hover:bg-orange-600 disabled:opacity-40">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : 'Analyse this job match'}</button><button onClick={() => saveMatch()} disabled={!result} className="inline-flex items-center gap-2 rounded-2xl border border-slate-200 bg-white px-5 py-3.5 text-sm font-black text-slate-700 disabled:opacity-40"><Copy className="h-4 w-4" /> Save tailored version</button><button onClick={generateLetter} disabled={!canAnalyse || letterLoading} className="inline-flex items-center gap-2 rounded-2xl bg-slate-950 px-5 py-3.5 text-sm font-black text-white disabled:opacity-40">{letterLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Mail className="h-4 w-4" />} Generate cover letter</button><Link to="/applications" className="rounded-2xl border border-slate-200 bg-white px-5 py-3.5 text-sm font-black text-slate-700">Application tracker</Link>{notice && <span className="text-sm font-bold text-emerald-700">{notice}</span>}</div>
  {result && <div className="mt-10 rounded-3xl border border-slate-200 bg-slate-50 p-5 sm:p-8"><JobMatchScoreBreakdown result={result} /><div className="mt-8 flex flex-col gap-4 rounded-2xl bg-white p-5 sm:flex-row sm:items-end"><div className="flex-1"><label className="text-xs font-black uppercase tracking-wider text-slate-500">Version name</label><input value={versionName} onChange={e => setVersionName(e.target.value)} placeholder={`${jobTitle} — tailored`} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm" /></div><button onClick={() => saveMatch()} className="rounded-xl bg-slate-950 px-5 py-3 text-sm font-black text-white">Save version</button></div></div>}
  {coverLetter && <section className="mt-8 rounded-3xl border border-orange-100 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center gap-3"><Mail className="text-orange-500" /><div><h2 className="text-xl font-black">Generated cover letter</h2><p className="text-sm text-slate-500">Review and edit before sending. AI output may need personalization.</p></div></div><div className="mt-5 space-y-3 rounded-2xl bg-slate-50 p-5 text-sm leading-7"><p className="font-black">{coverLetter.subject}</p><p>{coverLetter.salutation}</p><p>{coverLetter.introduction}</p><p>{coverLetter.bodyParagraph1}</p><p>{coverLetter.bodyParagraph2}</p><p>{coverLetter.conclusion}</p><p>{coverLetter.closing}</p></div><button onClick={() => saveMatch({ coverLetter })} className="mt-4 rounded-xl bg-orange-500 px-5 py-3 text-sm font-black text-white">Save with this match</button></section>}
  <section className="mt-10 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center gap-3"><History className="text-orange-500" /><div><h2 className="text-xl font-black">Saved applications and versions</h2><p className="text-sm text-slate-500">{user ? 'Stored securely with your account.' : 'Stored in this browser until you sign in.'}</p></div></div>{versions.length ? <div className="mt-5 grid gap-3 md:grid-cols-2">{versions.map(item => <div key={item._id} className="flex items-center justify-between gap-3 rounded-2xl border border-slate-200 p-4"><button onClick={() => load(item)} className="min-w-0 text-left"><p className="truncate font-black">{item.title || item.name}</p><p className="mt-1 text-xs text-slate-500">{item.company || item.role || 'Target role'} · {item.status || 'Saved'}{item.matchResult?.score ? ` · ${item.matchResult.score}% match` : ''}</p></button><div className="flex items-center gap-1"><select value={item.status || 'Saved'} onChange={e => updateStatus(item, e.target.value)} className="max-w-24 rounded-lg border border-slate-200 px-1 py-2 text-xs"><option>Saved</option><option>Applied</option><option>Screening</option><option>Interview</option><option>Offer</option><option>Rejected</option></select><button onClick={() => remove(item)} className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600" aria-label="Delete saved match"><Trash2 className="h-4 w-4" /></button></div></div>)}</div> : <div className="mt-5 rounded-2xl bg-slate-50 p-5 text-sm text-slate-600">Run your first analysis to create a saved application.</div>}</section><p className="mt-8 text-center text-xs leading-5 text-slate-500">Never add skills, metrics, or experience you cannot honestly support.</p></div></main></>;
}
