import { Link, useLocation } from 'react-router-dom';
import { ArrowRight, CheckCircle2, Code2, MessageCircleQuestion, Target } from 'lucide-react';
import SEO from '../components/SEO';

const pages = {
  '/interview-prep/software-engineer': { role: 'Software Engineer', slug: 'software-engineer-interview-preparation-guide', title: 'Software Engineer Interview Preparation Guide', description: 'Prepare for Software Engineer interviews with coding, system design, project, behavioral, and communication practice.', topics: ['Data structures and algorithms', 'Testing and debugging', 'System design and trade-offs', 'Project ownership and collaboration'], questions: ['How would you design a feature you recently worked on?', 'How do you test code and reason about edge cases?', 'Tell me about a difficult bug and your debugging process?', 'How would you explain a system design trade-off?'], resume: '/resume-guide/software-engineer' },
  '/interview-prep/frontend-developer': { role: 'Frontend Developer', slug: 'frontend-developer-interview-questions-preparation', title: 'Frontend Developer Interview Questions and Preparation', description: 'Practice JavaScript, React, accessibility, performance, debugging, project, and communication topics for Frontend Developer interviews.', topics: ['HTML, CSS, and JavaScript fundamentals', 'React architecture and state', 'Accessibility and browser behavior', 'Performance and frontend testing'], questions: ['How would you build an accessible responsive navigation?', 'How would you diagnose a slow page load?', 'How do component boundaries affect maintainability?', 'How would you test a frontend feature?'], resume: '/resume-guide/software-engineer' },
  '/interview-prep/backend-developer': { role: 'Backend Developer', slug: 'backend-developer-interview-questions-preparation', title: 'Backend Developer Interview Questions: APIs and Databases', description: 'Prepare for Backend Developer interviews with APIs, databases, concurrency, testing, debugging, and system design guidance.', topics: ['HTTP, APIs, and service design', 'Databases, indexes, and transactions', 'Caching, concurrency, and consistency', 'Authentication, testing, and observability'], questions: ['How would you design a scalable API?', 'How would you investigate a slow database query?', 'How do caching and consistency interact?', 'How would you test a backend system?'], resume: '/resume-guide/software-engineer' },
  '/interview-prep/data-analyst': { role: 'Data Analyst', slug: 'data-analyst-interview-questions-sql-case-study', title: 'Data Analyst Interview Questions: SQL and Case Studies', description: 'Practice SQL, case studies, metrics, data quality, visualization, and stakeholder communication for Data Analyst interviews.', topics: ['SQL joins, aggregations, and windows', 'Metrics and business case studies', 'Data quality and validation', 'Visualization and stakeholder communication'], questions: ['How would you investigate a sudden drop in a key metric?', 'How would you find top products by revenue for each month?', 'How do you choose a visualization for an audience?', 'How do you handle missing or duplicated data?'], resume: '/resume-guide/data-analyst' },
  '/interview-prep/devops-engineer': { role: 'DevOps Engineer', slug: 'devops-engineer-interview-questions-preparation', title: 'DevOps Engineer Interview Questions: Cloud and CI/CD', description: 'Prepare for DevOps Engineer interviews with Linux, cloud, CI/CD, infrastructure as code, observability, security, and incident response topics.', topics: ['Linux, networking, and systems', 'CI/CD and release strategies', 'Cloud and infrastructure as code', 'Observability, security, and incidents'], questions: ['How would you design a safe CI/CD pipeline?', 'How would you troubleshoot a host under resource pressure?', 'What makes an alert actionable?', 'How would you make infrastructure changes reviewable?'], resume: '/resume-builder-for-tech-jobs' }
};

const related = [['/interview-prep', 'Open Interview Prep'], ['/job-description-matcher', 'Match your resume to a job'], ['/resume-score-checker', 'Check resume clarity'], ['/blog', 'Read the interview blog'], ['/applications', 'Track applications']];

export default function TechInterviewLanding() {
  const path = useLocation().pathname;
  const page = pages[path] || pages['/interview-prep/software-engineer'];
  const url = `https://resumecraft.co.in${path}`;
  return <>
    <SEO title={page.title} description={page.description} keywords={`${page.role} interview questions, ${page.role} interview preparation, ${page.role} interview guide`} canonical={url} />
    <main className="bg-white text-slate-900">
      <section className="relative overflow-hidden bg-slate-950 px-4 py-20 text-white sm:px-6 lg:py-28"><div className="absolute -right-24 -top-24 h-96 w-96 rounded-full bg-orange-500/20 blur-3xl" /><div className="relative mx-auto max-w-5xl"><div className="flex items-center gap-3 text-sm font-black uppercase tracking-[0.2em] text-orange-300"><Code2 className="h-5 w-5" />{page.role} interview preparation</div><h1 className="mt-6 max-w-4xl text-4xl font-black tracking-tight sm:text-6xl">{page.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">{page.description} Use this as a practical checklist, then adapt it to the actual job description and interview format.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/interview-prep" className="inline-flex items-center rounded-2xl bg-orange-500 px-5 py-3.5 text-sm font-black hover:bg-orange-400">Practice interview questions <ArrowRight className="ml-2 h-4 w-4" /></Link><Link to={page.resume} className="rounded-2xl border border-white/20 px-5 py-3.5 text-sm font-black hover:bg-white/10">Prepare your resume</Link></div></div></section>
      <section className="mx-auto grid max-w-5xl gap-10 px-4 py-16 sm:px-6 lg:grid-cols-[.8fr_1.2fr] lg:py-24"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-orange-600">What to review</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Focus on the evidence you can explain.</h2><p className="mt-5 leading-7 text-slate-600">Strong preparation is specific, honest, and connected to your own projects. Review the areas most relevant to the job instead of trying to memorize every possible answer.</p></div><div className="grid gap-4 sm:grid-cols-2">{page.topics.map((topic) => <div key={topic} className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><CheckCircle2 className="h-5 w-5 text-orange-500" /><p className="mt-3 font-black text-slate-800">{topic}</p></div>)}</div></section>
      <section className="bg-orange-50 px-4 py-16 sm:px-6 lg:py-20"><div className="mx-auto max-w-5xl"><div className="flex items-center gap-3"><MessageCircleQuestion className="h-6 w-6 text-orange-600" /><h2 className="text-3xl font-black tracking-tight">Questions to practice</h2></div><div className="mt-7 grid gap-4 md:grid-cols-2">{page.questions.map((question, index) => <div key={question} className="rounded-2xl border border-orange-100 bg-white p-5"><span className="text-xs font-black uppercase tracking-widest text-orange-600">Question {index + 1}</span><p className="mt-3 font-bold leading-7 text-slate-800">{question}</p></div>)}</div><p className="mt-7 max-w-3xl text-sm leading-6 text-slate-600">When you do not know an answer, clarify the question, state an assumption, explain a possible approach, and describe how you would verify it. No preparation guide guarantees a job offer.</p></div></section>
      <section className="mx-auto max-w-5xl px-4 py-16 sm:px-6 lg:py-20"><div className="flex items-center gap-3"><Target className="h-6 w-6 text-orange-600" /><h2 className="text-3xl font-black tracking-tight">Continue your preparation</h2></div><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{related.map(([href, label]) => <Link key={href} to={href} className="rounded-2xl border border-slate-200 bg-white p-4 text-sm font-black text-slate-800 transition hover:-translate-y-0.5 hover:border-orange-300"><ArrowRight className="mb-3 h-5 w-5 text-orange-500" />{label}</Link>)}</div></section>
    </main>
  </>;
}
