import { Link, useNavigate, useParams } from 'react-router-dom';
import SEO from '../components/SEO';
import { ArrowRight, CheckCircle2 } from 'lucide-react';
import { createEmptyResume, TEMPLATE_OPTIONS } from '../data/resumeBuilder';
import { trackEvent } from '../utils/analytics';

const categories = {
  ats: { title: 'ATS-Friendly Resume Templates', description: 'Simple, readable templates with clear hierarchy for applications that use applicant tracking software.', bestFor: 'Candidates who want clean structure and reliable parsing.', notes: ['Standard section headings improve scanability.', 'Avoid columns, decorative graphics, and dense text when an ATS-readable layout is a priority.', 'Always compare keywords with the job description and keep every claim accurate.'] },
  fresher: { title: 'Resume Templates for Freshers', description: 'Education- and project-friendly templates for graduates and early-career candidates.', bestFor: 'Students, recent graduates, and candidates with limited full-time experience.', notes: ['Bring projects, internships, coursework, and relevant skills forward.', 'Use a summary that is specific to the target role.', 'Do not add skills just because a template suggests them.'] },
  student: { title: 'Student Resume Templates', description: 'Flexible layouts for students balancing academic work, projects, volunteering, and campus activities.', bestFor: 'College students preparing for internships or entry-level roles.', notes: ['Use the space to explain what you built or contributed to.', 'Keep education details concise and current.', 'Include links only when they work and represent you well.'] },
  'software-engineer': { title: 'Software Engineer Resume Templates', description: 'Technical layouts that make skills, projects, experience, and impact easy to review.', bestFor: 'Software engineers, developers, and technical candidates.', notes: ['Group tools and frameworks by what you can genuinely discuss.', 'Describe the problem and your contribution, not only the technology name.', 'Use metrics only when you know the source and context.'] },
  modern: { title: 'Modern Resume Templates', description: 'Contemporary layouts with restrained visual hierarchy and a polished presentation.', bestFor: 'Candidates who want a current look without sacrificing readability.', notes: ['Keep the accent color restrained.', 'Preview every page at A4 size before exporting.', 'Use consistent dates, punctuation, and spacing.'] },
  professional: { title: 'Professional Resume Templates', description: 'Structured templates for corporate, business, operations, and experienced roles.', bestFor: 'Professionals who want a clear, confident, recruiter-focused layout.', notes: ['Prioritize the most relevant work instead of listing everything.', 'Lead bullets with strong verbs and factual outcomes.', 'Keep seniority and scope clear without inflating responsibilities.'] },
};

const TemplateLanding = () => {
  const { slug } = useParams();
  const navigate = useNavigate();
  const category = categories[slug];
  const handleUseTemplate = () => {
    const template = TEMPLATE_OPTIONS.find((item) => item.category.toLowerCase().replace(/\s+/g, '-') === slug) || TEMPLATE_OPTIONS[0];
    localStorage.setItem('guest_resume_draft', JSON.stringify(createEmptyResume({ templateId: template.id, title: 'My Resume', customization: { accentColor: template.accent } })));
    trackEvent('template_selected', { template_id: template.id, category: slug });
    navigate('/editor');
  };

  if (!category) return <div className="mx-auto max-w-6xl px-4 py-24"><SEO title="Resume Templates" description="Explore ATS-friendly, modern, student, fresher, and professional resume templates." /><h1 className="text-4xl font-black text-slate-950">Resume templates</h1><p className="mt-4 text-slate-600">Choose a category to find a layout that matches your role and experience.</p><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(categories).map(([key, item]) => <Link key={key} to={`/resume-templates/${key}`} className="rounded-3xl border border-slate-200 bg-white p-5 transition hover:-translate-y-1 hover:border-orange-300 hover:shadow-xl"><h2 className="font-black text-slate-900">{item.title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{item.description}</p><span className="mt-5 inline-flex items-center text-sm font-black text-orange-600">Explore category <ArrowRight className="ml-1 h-4 w-4" /></span></Link>)}</div></div>;

  const template = TEMPLATE_OPTIONS.find((item) => item.category.toLowerCase().replace(/\s+/g, '-') === slug) || TEMPLATE_OPTIONS[0];
  return <div className="bg-white"><SEO title={category.title} description={category.description} keywords={`${category.title}, resume templates, ATS-friendly resume`} /><section className="bg-slate-950 px-4 py-20 text-white"><div className="mx-auto max-w-6xl"><p className="text-xs font-black uppercase tracking-[0.2em] text-orange-300">Resume templates</p><h1 className="mt-4 max-w-3xl text-4xl font-black tracking-tight sm:text-6xl">{category.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">{category.description}</p><button type="button" onClick={handleUseTemplate} className="mt-8 inline-flex items-center rounded-2xl bg-orange-500 px-5 py-3.5 text-sm font-black text-white hover:bg-orange-400">Build with this layout <ArrowRight className="ml-2 h-4 w-4" /></button></div></section><main className="mx-auto max-w-6xl px-4 py-14"><div className="grid gap-10 lg:grid-cols-[0.85fr_1.15fr]"><section><h2 className="text-2xl font-black text-slate-950">Who should use it?</h2><p className="mt-4 text-lg leading-8 text-slate-600">{category.bestFor}</p><h2 className="mt-12 text-2xl font-black text-slate-950">What makes this layout useful?</h2><div className="mt-5 space-y-4">{category.notes.map((note) => <p key={note} className="flex gap-3 text-sm leading-7 text-slate-600"><CheckCircle2 className="mt-1 h-5 w-5 shrink-0 text-emerald-500" />{note}</p>)}</div><div className="mt-12 flex flex-wrap gap-3"><Link to="/resume-examples" className="rounded-xl border border-slate-200 px-4 py-3 text-sm font-black text-slate-700 hover:border-orange-300">See resume examples</Link><Link to="/ats-resume-checker-preview" className="rounded-xl border border-slate-200 px-4 py-3 text-sm font-black text-slate-700 hover:border-orange-300">Review ATS guidance</Link></div></section><section className="rounded-3xl border border-slate-200 bg-slate-100 p-5 shadow-xl"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-orange-500">Template preview</p><h2 className="mt-1 text-xl font-black text-slate-950">{template.name}</h2></div><span className="rounded-full bg-white px-3 py-1 text-xs font-bold text-slate-500">Printable</span></div><div className="mx-auto max-h-[960px] max-w-2xl overflow-hidden rounded-xl bg-white"><div className="h-10" style={{ background: template.accent }} /><div className="p-8"><div className="h-4 w-1/2 rounded bg-slate-200" /><div className="mt-3 h-2 w-1/3 rounded bg-slate-100" /><div className="mt-8 space-y-5">{[1, 2, 3, 4, 5].map((item) => <div key={item}><div className="h-2 w-1/3 rounded bg-slate-200" /><div className="mt-3 space-y-2"><div className="h-1.5 rounded bg-slate-100" /><div className="h-1.5 w-11/12 rounded bg-slate-100" /><div className="h-1.5 w-4/5 rounded bg-slate-100" /></div></div>)}</div></div></div></section></div></main></div>;
};

export default TemplateLanding;
